const products = [
  {
    id: 1,
    name: "Fitch Long-Sleeve Rugby Polo",
    brandName: "Abercrombie",
    category: "Shirt",
    cost: 120,
    price: 40.7,
    stock: 50,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image1.jpg",
  },
  {
    id: 2,
    name: "Purl Knit Quarter-Zip Jumper",
    brandName: "Zara",
    category: "Shirt",
    cost: 49.9,
    price: 55.9,
    stock: 30,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image2.jpg",
  },
  {
    id: 3,
    name: "Preppy Tennis Johnny Collar",
    brandName: "Abercrombie & Fitch",
    category: "Shirt",
    cost: 51.79,
    price: 61.49,
    stock: 60,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image3.jpg",
  },
  {
    id: 4,
    name: "Boxy Pattern Sweater Polo",
    brandName: "Hollister Co",
    category: "Shirt",
    cost: 30.4,
    price: 39.95,
    stock: 30,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image4.jpg",
  },
  {
    id: 5,
    name: "Blue Bloom Cuban Shirt",
    brandName: "Da stalker",
    category: "Shirt",
    cost: 32.89,
    price: 40.99,
    stock: 48,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image5.jpg",
  },
  {
    id: 6,
    name: "Men's White Casual Ocean Wave",
    brandName: "EGNMCR",
    category: "Shirt",
    cost: 11.9,
    price: 25.9,
    stock: 30,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image6.jpg",
  },
  {
    id: 7,
    name: "Boys Thermal Polo Sweather",
    brandName: "S.Dr.Tomat",
    category: "Shirt",
    cost: 11.99,
    price: 20.99,
    stock: 159,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image7.jpg",
  },
  {
    id: 8,
    name: "Kotn x Barbarian Rugby Shirt",
    brandName: "Kotn",
    category: "Shirt",
    cost: 140.89,
    price: 160.99,
    stock: 18,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image8.jpg",
  },
  {
    id: 9,
    name: "Blouse in Wrap Look Striped",
    brandName: "BOSS (Hugo Boss)",
    category: "Shirt",
    cost: 250.99,
    price: 279.99,
    stock: 50,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image14.jpg",
  },
  {
    id: 10,
    name: "Cotton-blend Collar Striped",
    brandName: "Cider",
    category: "Shirt",
    cost: 15.99,
    price: 19.99,
    stock: 30,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image15.jpg",
  },
  {
    id: 11,
    name: "Contrast Collar Knotted Detail",
    brandName: "MICAS",
    category: "Shirt",
    cost: 28.8,
    price: 35.99,
    stock: 60,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image16.jpg",
  },
  {
    id: 12,
    name: "Tie-Waist Satin Sleeveless Wrap",
    brandName: "COMMENSE",
    category: "Shirt",
    cost: 34.4,
    price: 46.95,
    stock: 30,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image17.jpg",
  },
  {
    id: 13,
    name: "Contrast Collar Knotted Detail",
    brandName: "MICAS",
    category: "Shirt",
    cost: 28.89,
    price: 36.99,
    stock: 48,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image18.jpg",
  },
  {
    id: 14,
    name: "Contrast Collar Knotted Detail",
    brandName: "MICAS",
    category: "Shirt",
    cost: 28.95,
    price: 35.89,
    stock: 30,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image19.jpg",
  },
  {
    id: 15,
    name: "Oversized Knit Boat Neck Bowknot",
    brandName: "CIDER",
    category: "Shirt",
    cost: 18.99,
    price: 26.99,
    stock: 159,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image20.jpg",
  },
  {
    id: 16,
    name: "Stripes Print V-Neck Ruched",
    brandName: "Micas",
    category: "Shirt",
    cost: 26.75,
    price: 37.89,
    stock: 18,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image21.jpg",
  },
  //
  {
    id: 17,
    name: "Contrast Collar Knotted Detail",
    brandName: "MICAS",
    category: "Pants",
    cost: 28.99,
    price: 35.99,
    stock: 50,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image22.jpg",
  },
  {
    id: 18,
    name: "Printed Text Plush Joggers",
    brandName: "Zara",
    category: "Pants",
    cost: 19.99,
    price: 32.99,
    stock: 30,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image23.jpg",
  },
  {
    id: 19,
    name: "Moët Pintuck Balloon Wide Cotton",
    brandName: "BLACKUP GLOBAL",
    category: "Pants",
    cost: 45.8,
    price: 50.99,
    stock: 60,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image24.jpg",
  },
  {
    id: 20,
    name: " KIDS Pleated Wide Pants slash",
    brandName: "UNIQLO",
    category: "Pants",
    cost: 34.4,
    price: 46.95,
    stock: 30,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image25.jpg",
  },
  {
    id: 21,
    name: " Fleece Logo Graphic Shorts",
    brandName: "Hollister",
    category: "Pants",
    cost: 35.89,
    price: 39.99,
    stock: 48,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image26.jpg",
  },
  {
    id: 22,
    name: " Hollister Feel Good Fleece",
    brandName: "Hollister",
    category: "Pants",
    cost: 15.95,
    price: 20.89,
    stock: 30,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image27.jpg",
  },
  {
    id: 23,
    name: "H&M Kids Sweatshirt Cargo",
    brandName: "Sweatshirt Cargo Shorts",
    category: "Pants",
    cost: 10.99,
    price: 15.99,
    stock: 159,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image28.jpg",
  },
  {
    id: 24,
    name: "Hollister Feel Good Fleece",
    brandName: "Hollister",
    category: "Pants",
    cost: 34.75,
    price: 39.89,
    stock: 98,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image29.jpg",
  },
  //
  {
    id: 25,
    name: "Contrast Color Retro Skirt",
    brandName: "WhyBerry",
    category: "Pants",
    cost: 82.99,
    price: 99.99,
    stock: 50,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image30.jpg",
  },
  {
    id: 26,
    name: "High Waist Solid Pleated Pocket",
    brandName: "Cider",
    category: "Pants",
    cost: 18.99,
    price: 24.99,
    stock: 30,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image31.jpg",
  },
  {
    id: 27,
    name: "Woven Belted Mid Rise Bermuda",
    brandName: "Cider",
    category: "Pants",
    cost: 28.8,
    price: 35.99,
    stock: 60,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image32.jpg",
  },
  {
    id: 28,
    name: "Tulip Pleated Bermuda Shorts",
    brandName: "Balenciaga",
    category: "Pants",
    cost: 2700,
    price: 3000,
    stock: 6,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image33.jpg",
  },
  {
    id: 29,
    name: "Asymmetrical Corduroy Wrap",
    brandName: "Cider ",
    category: "Pants",
    cost: 18.89,
    price: 24.99,
    stock: 48,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image34.jpg",
  },
  {
    id: 30,
    name: "Rita High Waisted Flared Short",
    brandName: "Shona Joy",
    category: "Pants",
    cost: 240,
    price: 260,
    stock: 30,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image35.jpg",
  },
  {
    id: 31,
    name: "Solid Corduroy Pleated Belted",
    brandName: "Sweatshirt Cargo Shorts",
    category: "Pants",
    cost: 15.99,
    price: 28.99,
    stock: 159,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image36.jpg",
  },
  {
    id: 32,
    name: "High Waist Belted Wide Leg",
    brandName: "Ciber",
    category: "Pants",
    cost: 29.75,
    price: 25.89,
    stock: 98,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image37.jpg",
  },
  //
  {
    id: 33,
    name: "Strap Chunky Heeled Ankle Strap",
    brandName: "SHEIN",
    category: "Shoe",
    cost: 13.99,
    price: 18.99,
    stock: 50,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image38.jpg",
  },
  {
    id: 34,
    name: "Toe Ankle Strap Block Heel",
    brandName: "CHARLES & KEITH",
    category: "Shoe",
    cost: 75.99,
    price: 80.99,
    stock: 30,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image39.jpg",
  },
  {
    id: 35,
    name: "pair of strappy, square-toe block",
    brandName: "THE GLOW",
    category: "Shoe",
    cost: 50.8,
    price: 59.99,
    stock: 60,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image40.jpg",
  },
  {
    id: 36,
    name: "Mango Criss-Cross Straps Sandals",
    brandName: "MANGO",
    category: "Shoe",
    cost: 60.98,
    price: 76.99,
    stock: 6,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image41.jpg",
  },
  {
    id: 37,
    name: "Patent Leather Effect Heeled",
    brandName: "MANGO ",
    category: "Shoe",
    cost: 35.89,
    price: 66.99,
    stock: 48,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image42.jpg",
  },
  {
    id: 38,
    name: "Stradivarius Crossover Strap",
    brandName: "Stradivarius",
    category: "Shoe",
    cost: 22.25,
    price: 30.99,
    stock: 30,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image43.jpg",
  },
  {
    id: 39,
    name: "Jessie Square-Toe Sandals Heel",
    brandName: "Aeyde",
    category: "Shoe",
    cost: 125.99,
    price: 149.99,
    stock: 159,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image44.jpg",
  },
  {
    id: 40,
    name: " Mango Women Black Solid Block",
    brandName: "Mango",
    category: "Shoe",
    cost: 29.75,
    price: 25.89,
    stock: 98,
    status: "In Stock",
    type: "women",
    image: "../Image/Products/image45.jpg",
  },
  //
  {
    id: 41,
    name: "Nike Air Force 1 '07 (White/Black)",
    brandName: "Nike",
    category: "Shoe",
    cost: 115.99,
    price: 125.99,
    stock: 50,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image46.jpg",
  },
  {
    id: 42,
    name: "Nike Blazer Mid '77 Vintage",
    brandName: "Nike",
    category: "Shoe",
    cost: 105.99,
    price: 115.99,
    stock: 30,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image47.jpg",
  },
  {
    id: 43,
    name: "Air Jordan 1 Low DN6999-100",
    brandName: "Jordan",
    category: "Shoe",
    cost: 110.8,
    price: 125.99,
    stock: 60,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image48.jpg",
  },
  {
    id: 44,
    name: "Nike Air Force 1 '07 (Yellow)",
    brandName: "Nike",
    category: "Shoe",
    cost: 115.98,
    price: 120.99,
    stock: 6,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image49.jpg",
  },
  {
    id: 45,
    name: "Air Jordan 1 Retro High OG (Latte)",
    brandName: "Jordan ",
    category: "Shoe",
    cost: 167.89,
    price: 180.99,
    stock: 48,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image50.jpg",
  },
  {
    id: 46,
    name: "Air Jordan 1 Retro High OG (Latte)",
    brandName: "Jordan",
    category: "Shoe",
    cost: 180.25,
    price: 215.99,
    stock: 30,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image51.jpg",
  },
  {
    id: 47,
    name: "New Balance 550 (BB550LM1)",
    brandName: "New Balance",
    category: "Shoe",
    cost: 110.99,
    price: 120.99,
    stock: 159,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image52.jpg",
  },
  {
    id: 48,
    name: "Wmns 550 (Summer Fog Dusk Blue)",
    brandName: "New Balance",
    category: "Shoe",
    cost: 29.75,
    price: 25.89,
    stock: 98,
    status: "In Stock",
    type: "men",
    image: "../Image/Products/image53.jpg",
  },
];
export function pushProduct(p) {
  products.push(p);
}
export function getProducts() {
  return products;
}

const user = [];
export function pushUser(u) {
  user.push(u);
}
export function getUser() {
  return user;
}
